{
 "title": "EMR Spark Streaming",
 "tags": [
  "spark",
  "emr"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Running Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "RunningWorkerCount",
     "namespace": "AWS/EMRServerless",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "vCPUs Allocated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "CPUAllocated",
     "namespace": "AWS/EMRServerless",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "MemoryAllocated",
     "namespace": "AWS/EMRServerless",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Storage Allocated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "StorageAllocated",
     "namespace": "AWS/EMRServerless",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Worker & CPU Allocation (Over Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricName": "CPUAllocated",
     "namespace": "AWS/EMRServerless",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum",
     "label": "vCPUs"
    },
    {
     "metricName": "RunningWorkerCount",
     "namespace": "AWS/EMRServerless",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum",
     "label": "Workers"
    },
    {
     "metricName": "IdleWorkerCount",
     "namespace": "AWS/EMRServerless",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum",
     "label": "Idle Workers"
    }
   ]
  },
  {
   "title": "Memory & Storage Allocation (Over Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "metricName": "MemoryAllocated",
     "namespace": "AWS/EMRServerless",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum",
     "label": "Memory"
    },
    {
     "metricName": "StorageAllocated",
     "namespace": "AWS/EMRServerless",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum",
     "label": "Storage"
    }
   ]
  }
 ]
}